In [4]:
kaggle_qlib_dir = "/mnt/d/dataset/quant/kaggle22/qlib_format/"

In [3]:
import os
import pandas as pd
from pathlib import Path

'''
    stock_prices.csv转换成每只股票单独的csv
'''

stock_price_df = pd.read_csv("/mnt/d/dataset/quant/kaggle22/train_files/stock_prices.csv")
test_stock_price_df = pd.read_csv("/mnt/d/dataset/quant/kaggle22/supplemental_files/stock_prices.csv")

if not os.path.exists(kaggle_qlib_dir):
    os.makedirs(kaggle_qlib_dir)


def convert(df):
    df = df.rename(columns={"SecuritiesCode": "instrument", "Open": "open", "High": "high", "Low": "low", "Close": "close", "Volume": "volume", "AdjustmentFactor": "factor", "Date": "date"})
    for sc, group in df.groupby(['instrument']):
        group.to_csv(kaggle_qlib_dir + str(sc) + ".csv", header=True, index=False)


combined = pd.concat([stock_price_df, test_stock_price_df], axis=0)
# convert(combined)
convert(stock_price_df)
# convert(test_stock_price_df, "test_stock_prices.csv")

In [6]:
stock_price_df

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag,Target
0,20170104_1301,2017-01-04,1301,2734.0,2755.0,2730.0,2742.0,31400,1.0,NaN,False,0.000730
1,20170104_1332,2017-01-04,1332,568.0,576.0,563.0,571.0,2798500,1.0,NaN,False,0.012324
2,20170104_1333,2017-01-04,1333,3150.0,3210.0,3140.0,3210.0,270800,1.0,NaN,False,0.006154
3,20170104_1376,2017-01-04,1376,1510.0,1550.0,1510.0,1550.0,11300,1.0,NaN,False,0.011053
4,20170104_1377,2017-01-04,1377,3270.0,3350.0,3270.0,3330.0,150800,1.0,NaN,False,0.003026
...,...,...,...,...,...,...,...,...,...,...,...,...
2332526,20211203_9990,2021-12-03,9990,514.0,528.0,513.0,528.0,44200,1.0,NaN,False,0.034816
2332527,20211203_9991,2021-12-03,9991,782.0,794.0,782.0,794.0,35900,1.0,NaN,False,0.025478
2332528,20211203_9993,2021-12-03,9993,1690.0,1690.0,1645.0,1645.0,7200,1.0,NaN,False,-0.004302
2332529,20211203_9994,2021-12-03,9994,2388.0,2396.0,2380.0,2389.0,6500,1.0,NaN,False,0.009098
2332530,20211203_9997,2021-12-03,9997,690.0,711.0,686.0,696.0,381100,1.0,NaN,False,0.018414

In [7]:
%cd /mnt/d/code/quant/qlib

# qlib转换
!python scripts/dump_bin.py dump_all --csv_path {kaggle_qlib_dir} --qlib_dir ~/.qlib/qlib_data/kaggle --include_fields open,close,high,low,volume,factor,Target --symbol_field_name instrument --date_field_name date

/mnt/d/code/quant/qlib
2022-05-23 22:28:58.220 | INFO     | __main__:_get_all_date:272 - start get all date......
100%|██████████████████████████████████████| 2000/2000 [00:12<00:00, 160.77it/s]
2022-05-23 22:29:10.664 | INFO     | __main__:_get_all_date:291 - end of get all date.

2022-05-23 22:29:10.665 | INFO     | __main__:_dump_calendars:294 - start dump calendars......
2022-05-23 22:29:10.673 | INFO     | __main__:_dump_calendars:297 - end of calendars dump.

2022-05-23 22:29:10.673 | INFO     | __main__:_dump_instruments:300 - start dump instruments......
2022-05-23 22:29:10.677 | INFO     | __main__:_dump_instruments:302 - end of instruments dump.

2022-05-23 22:29:10.677 | INFO     | __main__:_dump_features:305 - start dump features......
100%|██████████████████████████████████████| 2000/2000 [00:09<00:00, 204.60it/s]
2022-05-23 22:29:20.453 | INFO     | __main__:_dump_features:312 - end of features dump.

In [8]:
%cd /mnt/d/code/quant/qlib
!python scripts/dump_bin.py dump_all --help

/mnt/d/code/quant/qlib
INFO: Showing help with the command 'dump_bin.py dump_all -- --help'.

NAME
    dump_bin.py dump_all

SYNOPSIS
    dump_bin.py dump_all COMMAND | VALUE | --csv_path=CSV_PATH --qlib_dir=QLIB_DIR <flags>

ARGUMENTS
    CSV_PATH
        Type: str
    QLIB_DIR
        Type: str

FLAGS
    --backup_dir=BACKUP_DIR
        Type: Optional[str]
        Default: None
    --freq=FREQ
        Type: str
        Default: 'day'
    --max_workers=MAX_WORKERS
        Type: int
        Default: 16
    --date_field_name=DATE_FIELD_NAME
        Type: str
        Default: 'date'
    --file_suffix=FILE_SUFFIX
        Type: str
        Default: '.csv'
    --symbol_field_name=SYMBOL_FIELD_NAME
        Type: str
        Default: 'symbol'
    --exclude_fields=EXCLUDE_FIELDS
        Type: str
        Default: ''
    --include_fields=INCLUDE_FIELDS
        Type: str
        Default: ''
    --limit_nums=LIMIT_NUMS
        Type: Optional[int]
        Default: None

COMMANDS
    COMMAND is one of the following:

     get_datetime_index

VALUES
    VALUE is one of the following:

     ALL_MODE

     CALENDARS_DIR_NAME

     DAILY_FORMAT

     DUMP_FILE_SUFFIX

     FEATURES_DIR_NAME

     HIGH_FREQ_FORMAT

     INSTRUMENTS_DIR_NAME

     INSTRUMENTS_END_FIELD

     INSTRUMENTS_FILE_NAME

     INSTRUMENTS_SEP

     INSTRUMENTS_START_FIELD

     UPDATE_MODE

In [9]:
index = ['Firefox', 'Chrome', 'Safari', 'IE10', 'Konqueror']
df = pd.DataFrame({'http_status': [200, 200, 404, 404, 301],
                  'response_time': [0.04, 0.02, 0.07, 0.08, 1.0]},
                  index=index)
df

           http_status  response_time
Firefox            200           0.04
Chrome             200           0.02
Safari             404           0.07
IE10               404           0.08
Konqueror          301           1.00

In [10]:
new_index = ['Safari', 'Iceweasel', 'Comodo Dragon', 'IE10', 'Chrome']
new_index = ['nowhere']
df.reindex(new_index)

         http_status  response_time
nowhere          NaN            NaN